#########################################
#
# Plugin made by rain_chat (v2.0 beta)
#
#
#########################################
Settings:
  # You can use custom language
  # language - En_en(English), Ru_ru(Русский)
  language: "En_en"
  max_energy: 20
  # I haven't added anything yet
  # but you can use soul or none(it disable particle)
  effect_stile: soul

ParkourSettings:
  Climbing:
    energy_need: 1.5

  Clinging:
    energy_need: 2

  Crawling:
    energy_need: 5
    boost: true

  Wall_jump:
    energy_need: 3.5

  Leap_Of_Faith:
    energy_need: 0

  Wall_kick:
    energy_need: 3.5

  Double_jump:
    energy_need: 6
    jump_high: 0.25

#########################################
#               Modules
#       Keep only what you need
#########################################
Modules:
  Climbing: true
  Clinging: true
  Crawling: true
  Leap_Of_Faith: true
  Wall_jump: true
  Wall_kick: true
  ######################################
  # Still not ready. not affect anything
  Wall_run: true
  # Not completed yet, has a lot of bugs. Use at your own risk
  Double_jump: false
  ######################################