name: SoulParkour
version: ${project.version}
main: com.rainchat.soulparkour.SoulParkourMain
api-version: 1.13
authors: [ rain_chat ]

commands:
  soulparkour:
    usage: /<command>
    aliases:
      - sp

permissions:

  # PLAYER PERMISSION
  soulparkour.use.*:
    default: op
    description: Gives the player access to all baseline permissions originally meant for a casual player.
    children:
      soulparkour.use.doublejump: true
      soulparkour.use.bounces: true
      soulparkour.use.grab: true
      soulparkour.use.leapoffaith: true
  soulparkour.admin.*:
    default: op
    description: only for admins.
    children:
      soulparkour.admin.reload: true